apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: puru-pet
  name: puru-pet
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  puru-pet
  template:
    metadata:
      labels:
        app:  puru-pet
    spec:
      containers:
      - image: purugcit79/puru:19
        name: pet
